### PR TITLE
Fix #793 - fix alignment of ettercap filters - update changelog

### LINKED ISSUE #793: multiple misaligned address error
On master at commit 7f50c57 :
(visible with the undefined behavior sanitizer)

```
# ettercap -F $FILE
ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1228:14: runtime error: member access within misaligned address 0x619000003351 for type 'struct filter_op', which requires 8 byte alignment
0x619000003351: note: pointer points here
 20 31 0a  00 01 00 00 00 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1228:14 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1228:21: runtime error: load of misaligned address 0x619000003351 for type 'char', which requires 8 byte alignment
0x619000003351: note: pointer points here
 20 31 0a  00 01 00 00 00 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1228:21 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:17: runtime error: member access within misaligned address 0x619000003351 for type 'struct filter_op', which requires 8 byte alignment
0x619000003351: note: pointer points here
 20 31 0a  00 01 00 00 00 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:17 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:24: runtime error: member access within misaligned address 0x619000003359 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003359: note: pointer points here
 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:24 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:27: runtime error: member access within misaligned address 0x619000003359 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:64:7)', which requires 8 byte alignment
0x619000003359: note: pointer points here
 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:27 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:32: runtime error: load of misaligned address 0x619000003381 for type 'size_t' (aka 'unsigned long'), which requires 8 byte alignment
0x619000003381: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 0f 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1237:32 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:17: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:17 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:24: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:24 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:27: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:27 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:32: runtime error: load of misaligned address 0x619000003449 for type 'size_t' (aka 'unsigned long'), which requires 8 byte alignment
0x619000003449: note: pointer points here
 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1230:32 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:72: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:72 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:79: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:79 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:82: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:82 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:87: runtime error: load of misaligned address 0x619000003441 for type 'u_int8 *' (aka 'unsigned char *'), which requires 8 byte alignment
0x619000003441: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:87 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:16: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:16 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:23: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:23 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:26: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:26 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:31: runtime error: store to misaligned address 0x619000003441 for type 'u_int8 *' (aka 'unsigned char *'), which requires 8 byte alignment
0x619000003441: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 09 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1231:31 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:17: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:17 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:24: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:24 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:27: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:27 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:32: runtime error: load of misaligned address 0x619000003459 for type 'size_t' (aka 'unsigned long'), which requires 8 byte alignment
0x619000003459: note: pointer points here
 00 00 00  00 08 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1232:32 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:73: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:73 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:80: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:80 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:83: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:83 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:88: runtime error: load of misaligned address 0x619000003451 for type 'u_int8 *' (aka 'unsigned char *'), which requires 8 byte alignment
0x619000003451: note: pointer points here
 00 00 00  00 09 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:88 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:16: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:16 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:23: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:23 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:26: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 09 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:26 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:31: runtime error: store to misaligned address 0x619000003451 for type 'u_int8 *' (aka 'unsigned char *'), which requires 8 byte alignment
0x619000003451: note: pointer points here
 00 00 00  00 09 00 00 00 00 00 00  00 08 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1233:31 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1269:10: runtime error: member access within misaligned address 0x619000003351 for type 'struct filter_op', which requires 8 byte alignment
0x619000003351: note: pointer points here
 20 31 0a  00 01 00 00 00 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1269:10 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1269:17: runtime error: load of misaligned address 0x619000003351 for type 'char', which requires 8 byte alignment
0x619000003351: note: pointer points here
 20 31 0a  00 01 00 00 00 00 00 00  00 00 03 01 00 09 00 00  00 06 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1269:17 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:17: runtime error: member access within misaligned address 0x619000003431 for type 'struct filter_op', which requires 8 byte alignment
0x619000003431: note: pointer points here
 00 00 00  00 05 00 00 00 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:17 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:24: runtime error: member access within misaligned address 0x619000003439 for type 'union (anonymous union at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:40:4)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 9f 32 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:24 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:27: runtime error: member access within misaligned address 0x619000003439 for type 'struct (anonymous struct at /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/include/ec_filter.h:42:7)', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 9f 32 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:27 in 
/tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:32: runtime error: load of misaligned address 0x619000003439 for type 'char', which requires 8 byte alignment
0x619000003439: note: pointer points here
 00 00 00  00 03 05 00 00 00 00 00  00 96 32 00 00 90 61 00  00 08 00 00 00 00 00 00  00 9f 32 00 00
              ^ 
SUMMARY: AddressSanitizer: undefined-behavior /tmp/portage/net-analyzer/ettercap-9999/work/ettercap-9999/src/ec_filter.c:1270:32 in 

Please select an User Interface
```

Reproducer:
[filter.ef.zip](https://github.com/Ettercap/ettercap/files/857953/filter.ef.zip)

### PR DESCRIPTION
**Pull request by koeppea**
This fixes issue #793.
The main issue is, that the instructions are not (if not by accident) aligned on the address-bus width boundary.
Fixing the issue is two-fold:
 1. check byte-alignment when reading filters
 2. compiling filters with aligned instructions

Unfortunately this implicitly leads to invalidate (nearly) all pre-compiled filters. They need to get recompiled from the filter-source to get a aligned filter. But this shouldn't be a big deal, since **ettercap** checks the version of the filter anyway.
 
This PR aligns the instructions on 8-byte boundary even though on 32-bit systems, 4-byte alignment would be sufficient.
However in order to maintain filters compiled on a 32-bit system able to run on a 64-bit system I stick to 8-byte since it's automatically a 4-byte alignment.

### CODE REVIEW

File: src/ec_filter.c [hunk 1]
```diff
@@ -1085,7 +1085,13 @@ int filter_load_file(const char *filename, struct filter_list **list, uint8_t en
...
    /* sanity checks */
    if (fh.magic != htons(EC_FILTER_MAGIC))
-      FATAL_MSG("Bad magic in filter file\nMake sure to compile the filter with etterfilter");
+      FATAL_MSG("Bad magic in filter file\n"
+            "Make sure to compile the filter with a current version of etterfilter");
+
+   /* check pointer alignment */
+   if (fh.code % 8)
+      FATAL_MSG("Bad instruction pointer alignment\n"
+            "Make sure to compile the filter with a current version of etterfilter");
```
Comment (sgeto) [inline src/ec_filter.c]: The wording is not clear. The _current_ version is the last released version, which obviously still has this issue.

Comment (koeppea) [reply src/ec_filter.c]: Do you have a suggestion? 

I tried to formulate in a way that doesn’t require frequent adjustments or confuses even more.

Maybe I should additionally drop a note in the CHANGES file which acts as a sort of release notes.

What do you think?

Comment (sgeto) [reply src/ec_filter.c]: A note in CHANGES or even README is a good idea. This is a big change after all.
A git tag may be helpful as well.

**Comment by koeppea** [comment]
Puh, I'm not familiar with Github Tags at all.

**Comment by koeppea** [comment]
Will update the CHANGES file....

**Comment by sgeto** [comment]
> Puh, I'm not familiar with Github Tags at all.

It's a Kinderspiel. And that's coming from me. 😄

**Comment by koeppea** [comment]
We'll make up a new pull request adjusting the copyright date and the CHANGE log as one of the last pull requests before the new release.
I'll rename this pull request again, that the note is not forgotten then.

**Comment by sgeto** [comment]
Will you keep this PR open or merge it until then?

**Comment by koeppea** [comment]
When it's good for merge it can be merged and closed. for the changelog of the new release, we'll go through the closed pull requests to get the changes.

**Comment by koeppea** [comment]
@eaescob ready to merge from my side. Are you also happy?

**Comment by eaescob** [comment]
Can you please update CHANGES file?

**Comment by koeppea** [comment]
> Can you please update CHANGES file?

Just dedicated #873 which includes the note about this caveat.
Merging now...
